 #include "../Inc/init.h";
  void GPIO_Ini(void){
   SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOBEN | RCC_AHB1ENR_GPIOCEN); //включение тактироания gpiob и gpioc
   SET_BIT(GPIOB->MODER, GPIO_MODER_MODE7_0);

   CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT7); //настройка на PP работу 7 пина GPIOB 
   SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR7_0);//настройка скорости работы 7 пина на средн
   CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPD7_0); //откл PU/PD резисторов для 7 пина  
 }
 //PB0
void Green_LED_ON(void){
   SET_BIT(GPIOB->MODER, GPIO_MODER_MODE0_0);
   CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT0); //настройка на PP работу 7 пина GPIOB 
   SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR0_0);//настройка скорости работы 7 пина на средн
   CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPD0_0); //откл PU/PD резисторов для 7 пина  
 }
 void Blue_LED_ON(void){
   SET_BIT(GPIOB->MODER, GPIO_MODER_MODE7_0);
   CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT7); //настройка на PP работу 7 пина GPIOB 
   SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR7_0);//настройка скорости работы 7 пина на средн
   CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPD7_0); //откл PU/PD резисторов для 7 пина  
 }
 void Red_LED_ON(void){
   SET_BIT(GPIOB->MODER, GPIO_MODER_MODE14_0);
   CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT14); //настройка на PP работу 7 пина GPIOB 
   SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR14_0);//настройка скорости работы 7 пина на средн
   CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPD14_0); //откл PU/PD резисторов для 7 пина  
 }


 void GPIOC10_Set_Output(void){
    SET_BIT(GPIOB->MODER, GPIO_MODER_MODE10_0);
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT10);
    SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR10_0);

    CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPD10_0);
 }
  void GPIOC10_Set_Input(void){
    CLEAR_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPDR10_0);
    CLEAR_BIT(GPIOC->MODER, GPIO_MODER_MODE10_0 );
    CLEAR_BIT(GPIOC->OSPEEDR, GPIO_OSPEEDER_OSPEEDR10_0);
 }
  void GPIOC11_Set_Output(void){
    SET_BIT(GPIOB->MODER, GPIO_MODER_MODE11_0);
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT11);
    SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR11_0);

    CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPD11_0);
 }
  void GPIOC11_Set_Input(void){
    CLEAR_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPDR11_0);
    CLEAR_BIT(GPIOC->MODER, GPIO_MODER_MODE11_0 );
    CLEAR_BIT(GPIOC->OSPEEDR, GPIO_OSPEEDER_OSPEEDR11_0);
 }
  void GPIOC12_Set_Output(void){
    SET_BIT(GPIOB->MODER, GPIO_MODER_MODE12_0);
    CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT12);
    SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR12_0);

    CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPD12_0);
 }
  void GPIOC12_Set_Input(void){
    CLEAR_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPDR12_0);
    CLEAR_BIT(GPIOC->MODER, GPIO_MODER_MODE12_0 );
    CLEAR_BIT(GPIOC->OSPEEDR, GPIO_OSPEEDER_OSPEEDR12_0);
 }