#include "init.h"

// PB0 - зеленый светодиод
void Green_LED_ON(void){
   SET_BIT(GPIOB->MODER, GPIO_MODER_MODER0_0);
   CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_0);
   SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR0_0);
   CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR0_0);
}

// PB7 - синий светодиод
void Blue_LED_ON(void){
   SET_BIT(GPIOB->MODER, GPIO_MODER_MODER7_0);
   CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_7);
   SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR7_0);
   CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR7_0);
}

// PB14 - красный светодиод
void Red_LED_ON(void){
   SET_BIT(GPIOB->MODER, GPIO_MODER_MODER14_0);
   CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT_14);
   SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR14_0);
   CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR14_0);
}

// PC10
void GPIOC10_Set_Output(void){
    SET_BIT(GPIOC->MODER, GPIO_MODER_MODER10_0);
    CLEAR_BIT(GPIOC->OTYPER, GPIO_OTYPER_OT_10);
    SET_BIT(GPIOC->OSPEEDR, GPIO_OSPEEDER_OSPEEDR10_0);
    CLEAR_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPDR10_0);
}

void GPIOC10_Set_Input(void){
    CLEAR_BIT(GPIOC->MODER, GPIO_MODER_MODER10_0);
    CLEAR_BIT(GPIOC->OSPEEDR, GPIO_OSPEEDER_OSPEEDR10_0);
    CLEAR_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPDR10_0);
}

// PC11
void GPIOC11_Set_Output(void){
    SET_BIT(GPIOC->MODER, GPIO_MODER_MODER11_0);
    CLEAR_BIT(GPIOC->OTYPER, GPIO_OTYPER_OT_11);
    SET_BIT(GPIOC->OSPEEDR, GPIO_OSPEEDER_OSPEEDR11_0);
    CLEAR_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPDR11_0);
}

void GPIOC11_Set_Input(void){
    CLEAR_BIT(GPIOC->MODER, GPIO_MODER_MODER11_0);
    CLEAR_BIT(GPIOC->OSPEEDR, GPIO_OSPEEDER_OSPEEDR11_0);
    CLEAR_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPDR11_0);
}

// PC12
void GPIOC12_Set_Output(void){
    SET_BIT(GPIOC->MODER, GPIO_MODER_MODER12_0);
    CLEAR_BIT(GPIOC->OTYPER, GPIO_OTYPER_OT_12);
    SET_BIT(GPIOC->OSPEEDR, GPIO_OSPEEDER_OSPEEDR12_0);
    CLEAR_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPDR12_0);
}

void GPIOC12_Set_Input(void){
    CLEAR_BIT(GPIOC->MODER, GPIO_MODER_MODER12_0);
    CLEAR_BIT(GPIOC->OSPEEDR, GPIO_OSPEEDER_OSPEEDR12_0);
    CLEAR_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPDR12_0);
}

//PC13 - кнопка на плате
void GPIOC13_Set_Input(void){
    CLEAR_BIT(GPIOC->MODER, GPIO_MODER_MODER13_0 | GPIO_MODER_MODER13_1);
    CLEAR_BIT(GPIOC->OSPEEDR, GPIO_OSPEEDER_OSPEEDR13_0 | GPIO_OSPEEDER_OSPEEDR13_1);
    // Включить подтягивающий резистор вверх
    //SET_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPDR13_0);
}
